name: Test Action

on:
  push:
    branches:
      - main  # Change to the branch you want to trigger the action on

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f3003934@ds.study.iitm.ac.in
        run: echo "Hello, world!"
